name: Test

on: [push]

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js and NPM
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: install dependencies
        run: npm install --save-dev

      - name: build
        run: npm run build

      - name: test
        run: npm test

  linter:
    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
      - name: linter
        run: npm run lint

      - name: ts checks
        run: npm exec tsc

  package:
    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
      - name: package
        run: npm run package
